spring:
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update  # o 'create', si quieres recrear desde cero
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

app:
  rabbitmq:
    queue: charge.queue